### PR TITLE
add coop menu

### PR DESCRIPTION
**Pull request by IruzzArcana**
adds an option to select the number of players in both the load confirm menu and after selecting the difficulty, in addition to costume selection.

### CODE REVIEW

**Comment by dawndus** [comment]
Nice work, few suggestions. 

1. Player count choice should always go *after* you pick "Start Game". Right now you're asked after starting a new game but along side loading a save? Should be similar, just put it after you load. (That's also how nicalis handles it on the Switch port.)
2. Maybe it's just me, but `PlayerNumber` sounds like it's talking about that specific player's number 1P or 2P, rather than the number of players. `PlayerCount` would make more sense for the enum.

**Comment by IruzzArcana** [comment]
Thanks, and yes you're right, I should've put it after selecting Start Game, I forgot how the Switch version handled it. I'll fix that right now.

**Comment by Awesomegamer6566** [comment]
Just thought I would point this out, selecting two players will also effect challenges.

https://user-images.githubusercontent.com/50709579/174831489-393dbe1c-820e-4f65-a2f2-ba46409b16fd.mp4

**Comment by IruzzArcana** [comment]
TODO: need to fix appearance showing the wrong skins for challenges that use different mychar (such as curly story or machine gun challenge)

https://user-images.githubusercontent.com/89710975/174966906-0c67e63b-d16b-449a-b3b7-4553c6d99654.mp4

**Comment by IruzzArcana** [comment]
Coincidentally, by fixing the skin selection menu I also ended up fixing Curly Story showing the wrong sprite in the save selection.

**Before**
Wed Jun 22 06:42:22 PM CET 2022

**After**
Wed Jun 22 06:42:36 PM CET 2022

**Comment by dawndus** [comment]
Need to tackle #107 now

**Pull request merged**
