### PR TITLE
Add various code clean-ups

### PR DESCRIPTION
**Pull request by tranzystorek-io**
Highlights:

- Use `IntoIterator` to shorten loop code
- Use `Deref` to simplify some pattern matching

### CODE REVIEW

**Comment by tranzystorek-io** [comment]
The second commit is just a run of `cargo fmt`, if this project has other style conventions please let me know.

**Comment by alula** [comment]
The first commit looks good, although I don't like usage of `any(||)` lambdas in controller code.

The project is supposed to use the rustfmt.toml config in root directory, but it has not been fully reformatted yet for certain reasons and I would like to do it later on my own, after merging other changes. 

Could you revert it then?

**Comment by alula** [comment]
Also I don't really like that you changed `n > x && n < y` expression's into `Range::contains` since it might feel less obvious for people who don't really know Rust.

**Comment by tranzystorek-io** [comment]
Just reverted the whole reformat as well as the 2 changes you mentioned 😃

**Comment by alula** [comment]
You've changed the `AsRef` trait call on `Option` to `RwLockReadGuard` borrow which broke the Android build... 

```
  --> /home/alula/workspace/doukutsu-rs/src/framework/backend_glutin.rs:36:17
   |
35 |             match &ndk_glue::native_window() {
   |                   -------------------------- this expression has type `&RwLockReadGuard<'_, std::option::Option<ndk::native_window::NativeWindow>>`
36 |                 Some(_) => {
   |                 ^^^^^^^ expected struct `RwLockReadGuard`, found enum `std::option::Option`
   |
   = note: expected struct `RwLockReadGuard<'_, std::option::Option<ndk::native_window::NativeWindow>, >`
                found enum `std::option::Option<_>`
```

**Comment by tranzystorek-io** [comment]
> You've changed the `AsRef` trait call on `Option` type stored inside to `RwLockReadGuard` borrow which broke the Android build...

Sorry! Rust analyzer was silent about this code because it's not the default target so I missed it. Reverted now 😅

**Review by alula — APPROVED** [review]
looks good now

**Pull request merged**
