### PR TITLE
Add Extras menu

### PR DESCRIPTION
**Pull request by Awesomegamer6566**
Includes the fix from https://github.com/doukutsu-rs/doukutsu-rs/pull/161
The ??? option changes the more_rust setting but ~~I can't find out why~~ it dosen't actually effect anything since it's linked to the debug menu. Also, turning debug mode off won't remove the debug menu if it's still open.
image

### CODE REVIEW

**Comment by Awesomegamer6566** [comment]
Ok. Maybe there can be a unique unlock condition for the more_rust thing like playing on July 7th but im not sure what would happen with the debug option.

**Comment by dawndus** [comment]
Both can be enabled in the config file directly as-is.

**Comment by Awesomegamer6566** [comment]
Well this is more of a template. I guess more stuff could be added in the future.

**Comment by dawndus** [comment]
Both are settings we hide on purpose, debug menu is hidden away so F-keys don't make unexpected things happen, more_rust is a fun Easter egg

**Comment by jozsefsallai** [comment]
Since these options are intentionally hidden from the UI, I think I'll close this PR. I merged the other one, however.

**Pull request closed without merging**
